### ISSUE TITLE
Template from String

### ISSUE THREAD

**Issue by RevoSolutionsLimited** [Atrociously/stilts#3]
Hello,

I'm using **pulldown-cmark** in one of my projects which renders common markup to an HTML String. It would be nice if one could register a template using a string (build time is fine) instead of a path on disk. Right now I'm just skipping escaping everything which is obviously not ideal, albeit not dangerous for the use case.

Thank you!

**Comment by Atrociously** [comment]
Hi thanks for opening an issue.

Do you mean adding something like this to use a literal string instead of a file?
```rust
#[derive(Template)]
#[stilts(content = "My Template Content {% data %}")]
struct MyTemplate {
    data: String,
}
```

I'm not sure what you mean with the escaping thing though.

**Comment by RevoSolutionsLimited** [comment]
Hi again, yes indeed, something like this will do perfectly. This way I could use it easily with my **proc_macros** to add content at compile time. Right now I'm injecting HTML at runtime, hence the escaping part.

Thanks a bunch for this wonderful library, I tried pretty much every single templating library in Rust, but they were all lacking except for Stilts. I'm really loving it and using it on two of my projects already, great job!

**Comment by Atrociously** [comment]
Ah I think I see what you mean with the escaping now, if you want to disable escape for individual items you can call [`DisplayExt::safe`](https://docs.rs/stilts/latest/stilts/trait.DisplayExt.html#tymethod.safe) on any type that implements Display within template code as the trait is pulled into scope. Also I will work on adding that feature I have already messed around with it a little bit, but now with a reason I'll get it done. Also thank you for the praise I really liked Askama but I just couldn't use enough rust inside the templates.

**Comment by Atrociously** [comment]
I just pushed out an update that adds support for the `content` attribute and some popular web framework integrations.

**Comment by RevoSolutionsLimited** [comment]
Thanks a lot, looking forward to using this feature this weekend for my development blog!
